image:
  repository: kong/kong-gateway
  tag: "3.4"

secretVolumes:
- kong-cluster-cert

admin:
  enabled: false


env:
  role: data_plane
  database: "off"
  cluster_mtls: pki
  cluster_control_plane: 43f3c632c7.eu.cp0.konghq.com:443
  cluster_server_name: 43f3c632c7.eu.cp0.konghq.com
  cluster_telemetry_endpoint: 43f3c632c7.eu.tp0.konghq.com:443
  cluster_telemetry_server_name: 43f3c632c7.eu.tp0.konghq.com
  cluster_cert: /etc/secrets/kong-cluster-cert/tls.crt
  cluster_cert_key: /etc/secrets/kong-cluster-cert/tls.key
  lua_ssl_trusted_certificate: system
  konnect_mode: "on"


ingressController:
  enabled: false
  installCRDs: false
